### PR TITLE
Show missing data

### LINKED ISSUE #83: Force show entire autosome

### PR DESCRIPTION
**Pull request by anderspitman**
Fixes #83

### CODE REVIEW

**Comment by anderspitman** [comment]
Pinging @AlistairNWard @chmille4 this is ready for review/merge. No rush on my end just wanted to make sure you know it's good to go.

**Comment by chmille4** [comment]
Thanks Anders, sorry for the slowness on our end.

**Comment by anderspitman** [comment]
No worries. Just wasn't sure if the status was clear after the flurry of waffle.io status changes from @AlistairNWard and me.

**Comment by chmille4** [comment]
Looks good!

**Pull request merged**
